"""empty message

Revision ID: ece6eed947b6
Revises: eca938e34614
Create Date: 2025-01-16 14:07:41.661828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece6eed947b6'
down_revision: Union[str, None] = 'eca938e34614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_users', 'chat', ['first_user_id', 'second_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_users', 'chat', type_='unique')
    # ### end Alembic commands ###
