"""empty message

Revision ID: a8cd983e5614
Revises: c3565f3251c0
Create Date: 2025-01-06 17:03:02.562231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8cd983e5614'
down_revision: Union[str, None] = 'c3565f3251c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'static/img/user_logo.png'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'static/img/user_logo.png'::character varying"))
    # ### end Alembic commands ###
