"""empty message

Revision ID: eca938e34614
Revises: 877e4db3c69e
Create Date: 2025-01-07 11:16:39.500422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca938e34614'
down_revision: Union[str, None] = '877e4db3c69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'static/img/user_logo.png'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'static/img/user_logo.png'::character varying"))
    # ### end Alembic commands ###
