"""empty message

Revision ID: 6114cab382aa
Revises: 17819bd8311a
Create Date: 2025-01-18 14:58:33.243407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6114cab382aa'
down_revision: Union[str, None] = '17819bd8311a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'first_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chat', 'second_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('chat_second_user_id_fkey', 'chat', type_='foreignkey')
    op.drop_constraint('chat_first_user_id_fkey', 'chat', type_='foreignkey')
    op.create_foreign_key(None, 'chat', 'users', ['second_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'chat', 'users', ['first_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.create_foreign_key('chat_first_user_id_fkey', 'chat', 'users', ['first_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('chat_second_user_id_fkey', 'chat', 'users', ['second_user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chat', 'second_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat', 'first_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
