"""empty message

Revision ID: 17819bd8311a
Revises: ece6eed947b6
Create Date: 2025-01-18 14:55:11.213893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17819bd8311a'
down_revision: Union[str, None] = 'ece6eed947b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('message_sender_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_sender_id_fkey', 'message', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.alter_column('message', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
